name: TDS Assignment Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3003311@ds.study.iitm.ac.in
        run: echo "Hello, world!"
